stages:          
  - build
  - test
  - deploy
 
default:
    image: docker:24.0.5
    services:
      - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  before_script:
#  - docker login registry.ci.warspoon.ru -u Deployer -p ${ACCESS_TOKEN}  
   - docker login -u warspoon3000 -p ${ACCESS_TOKEN} 
  script:
  #  - docker build -t registry.ci.warspoon.ru/root/test:${CI_COMMIT_SHORT_SHA} .
  #  - docker push registry.ci.warspoon.ru/root/test:${CI_COMMIT_SHORT_SHA}
  - docker build -t warspoon3000/skilbox:${CI_COMMIT_SHORT_SHA} .
  - docker push warspoon3000/skilbox:${CI_COMMIT_SHORT_SHA}

test:
  stage: test       
  script:
    - sh run-tests.sh   

deploy:      
  stage: deploy  
  only:
    - main
    - uat    
  image: warspoon3000/ansible_image:latest
  before_script:
    - ansible --version
    - mkdir secret
    - echo "$ANSIBLE_SSHKEY" > secret/ansible.key
    - chmod 400 secret/ansible.key
    - export ANSIBLE_HOST_KEY_CHECKING=False 
    - docker login -u warspoon3000 -p ${ACCESS_TOKEN}    
  script:    
#    - docker pull registry.ci.warspoon.ru/root/test:${CI_COMMIT_SHORT_SHA}
    - docker pull warspoon3000/skilbox:${CI_COMMIT_SHORT_SHA}     
    - ansible-playbook -b --private-key secret/ansible.key --user ubuntu -i ./ansible/hosts ./ansible/docker_playbook.yml