stages:          
  - build
  - test
  - deploy

#before_script:
#  - docker login -u Deployer -p ${ACCESS_TOKEN} gitlab.skillbox.ru/aleksei_koptev/ #ci.warspoon.ru  
default:
    image: docker:24.0.5
    services:
      - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  script:
    - docker build -t skillbox/app:${CI_COMMIT_SHORT_SHA} .

#build-docker:
#  stage: build
#  image: docker:stable
#  only:
#    - main    
#    - uat
#  services:
#    - docker:dind
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#  script:
#    - docker build . -t skillbox/app:${CI_COMMIT_SHORT_SHA}
 #  - docker tag skillbox/app:${CI_COMMIT_SHORT_SHA}
 #   - docker push skillbox/app:${CI_COMMIT_SHORT_SHA}

test:
  stage: test       
  script:
    - sh run-tests.sh   

deploy:      
  stage: deploy  
  only:
    - main
    - uat    
  image: warspoon3000/ansible_image:latest
  before_script:
    - ansible --version
    - mkdir secret
    - echo "$ANSIBLE_SSHKEY" > secret/ansible.key
    - chmod 400 secret/ansible.key
    - export ANSIBLE_HOST_KEY_CHECKING=False    
  script:
#    - docker pull skillbox/app:${CI_COMMIT_SHORT_SHA}     
    - ansible-playbook -b --private-key secret/ansible.key --user ubuntu -i ./ansible/hosts ./ansible/docker_playbook.yml
