stages:          
  - build
  - test
  - deploy

#before_script:
#  - docker login -u Deployer -p ${ACCESS_TOKEN} gitlab.skillbox.ru/aleksei_koptev/ #ci.warspoon.ru  

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  tags:
    - docker
  script:
    - docker build -t skillbox/app:${CI_COMMIT_SHORT_SHA} .

#build-docker:
#  stage: build
#  image: docker:stable
#  only:
#    - main    
#    - uat
#  services:
#    - docker:dind
#  variables:
#    DOCKER_HOST: tcp://docker:2375
#  script:
#    - docker build . -t skillbox/app:${CI_COMMIT_SHORT_SHA}
 #  - docker tag skillbox/app:${CI_COMMIT_SHORT_SHA}
 #   - docker push skillbox/app:${CI_COMMIT_SHORT_SHA}

test:
  stage: test       
  script:
    - sh run-tests.sh   

deploy:      
  stage: deploy
  only:
    - main
    - uat  
  when: always
  script:
#    - docker pull skillbox/app:${CI_COMMIT_SHORT_SHA} 
    - ansible-playbook -b ansible/docker_playbook.yml
