stages:          
  - build
  - test
  - deploy
 
default:
    image: docker:24.0.5
    services:
      - docker:24.0.5-dind

build:
  stage: build
  before_script:
#   - docker login registry.ci.warspoon.ru -u Deployer -p ${ACCESS_TOKEN}  
    - docker login -u ${DOCKER_HUB} -p ${ACCESS_TOKEN} 
  script:
#   - docker build -t registry.ci.warspoon.ru/root/test:${CI_COMMIT_SHORT_SHA} .
#   - docker push registry.ci.warspoon.ru/root/test:${CI_COMMIT_SHORT_SHA}    
    - docker build -t ${DOCKER_HUB}/skillbox:${CI_COMMIT_SHORT_SHA} .
    - docker push ${DOCKER_HUB}/skillbox:${CI_COMMIT_SHORT_SHA}

test:
  stage: test       
  script:
    - sh run-tests.sh   

deploy stage:      
  stage: deploy 
  image: warspoon3000/ansible_image:latest 
  only:
#   - main
    - uat      
  script:  
    - eval $(ssh-agent -s)
    - echo "$ANSIBLE_SSHKEY" | tr -d '\r'  > /tmp/id_rsa
    - chmod 600 /tmp/id_rsa
    - ssh-add /tmp/id_rsa
    - mkdir -p $HOME/.ssh
    - ssh-keyscan -H $STAGE >> $HOME/.ssh/known_hosts        
    - ansible-playbook -b --private-key /tmp/id_rsa --user ubuntu\
      -i ./ansible/inventory/stage\
      ./ansible/docker_playbook.yml\
      -e "docker_hub=${DOCKER_HUB} image_tag=${CI_COMMIT_SHORT_SHA} password=${ACCESS_TOKEN} port="8080:8080"" -vv

deploy prod:      
  stage: deploy 
  image: warspoon3000/ansible_image:latest 
  only:
    - main     
  script:  
    - eval $(ssh-agent -s)
    - echo "$ANSIBLE_SSHKEY" | tr -d '\r'  > /tmp/id_rsa
    - chmod 600 /tmp/id_rsa
    - ssh-add /tmp/id_rsa
    - mkdir -p $HOME/.ssh
    - ssh-keyscan -H $PROD >> $HOME/.ssh/known_hosts        
    - ansible-playbook -b --private-key /tmp/id_rsa --user ubuntu\
      -i ./ansible/inventory/prod\
      ./ansible/docker_playbook.yml\
      -e "docker_hub=${DOCKER_HUB} image_tag=${CI_COMMIT_SHORT_SHA} password=${ACCESS_TOKEN}port="80:80"" -vv
  when: manual 