---
- hosts: 127.0.0.1  

  vars:
    docker_hub: hub
    image_tag: tag

  tasks:
    - name: Pull an image
      community.docker.docker_image:
        name: "{{docker_hub}}/skillbox:{{image_tag}}"
        source: pull
    
    - name: run the image
      docker_container:
        name: skillbox-app
        image: "{{docker_hub}}/skillbox:{{image_tag}}"
        state: started
        ports: 8080:8080   
