---
- hosts: all
  remote_user: ubuntu  

  vars:
    docker_hub: hub
    image_tag: tag    
    password: password
    port: port

  tasks:
    - name: Docker login
      community.docker.docker_login:
        username: "{{docker_hub}}"
        password: "{{password}}"        

    - name: Pull an image
      community.docker.docker_image:
        name: "{{docker_hub}}/skillbox:{{image_tag}}"
        source: pull

    - name: Docker unlogin
      community.docker.docker_login:        
        username: "{{docker_hub}}"
        password: "{{password}}"
        state: absent
    
    - name: run the image
      community.docker.docker_container:
        name: skillbox-app
        image: "{{docker_hub}}/skillbox:{{image_tag}}"
        state: started
        ports: "{{port}}"   

    - name: copy unit
      ansible.builtin.copy:
        src: ./file/start-docker.service
        dest: /etc/systemd/system/start-docker.service

    - name: Enabled service
      ansible.builtin.service:
        name: start-docker
        enabled: yes
