---
- hosts: servers
  remote_user: ubuntu

  vars:
    release_path: /home/ubuntu/docker
    repositiry: https://gitlab.skillbox.ru/aleksei_koptev/service.git
    name_image: skillbox/app
    version: latest

  tasks:   
    - name: run the image
      docker_container:
        name: skillbox-app
        image: "{{ name_image }}"
        state: started
        ports: 8080:8080        
