---
- hosts: servers
  remote_user: ubuntu

  vars:
    release_path: /home/ubuntu/docker
    repositiry: https://gitlab.skillbox.ru/aleksei_koptev/service.git
    name_image: skillbox/app
    version: latest

  tasks:
#install skillbox-dockers        
    - name: Clone the repository
      git:
        repo: "{{ repositiry }}"
        dest: "{{ release_path }}"
      ignore_errors: true
    
    - name: Build the image
      docker_image:
        name: "{{ name_image }}"
        build:
          path: "{{ release_path }}"
        state: present
        source: build
        tag: "{{ version }}" 