---
- hosts: servers
  remote_user: ubuntu

  vars:
    release_path: /home/ubuntu/docker
    repositiry: https://gitlab.skillbox.ru/aleksei_koptev/service.git
    name_image: skillbox/app
    version: latest

  tasks:
#install skillbox-dockers        
    - name: Clone the repository
      git:
        repo: "{{ repositiry }}"
        dest: "{{ release_path }}"
      ignore_errors: true
    
    - name: Build the image
      docker_image:
        name: "{{ name_image }}"
        build:
          path: "{{ release_path }}"
        state: present
        source: build
        tag: "{{ version }}" 
    
    - name: run the image
      docker_container:
        name: skillbox-app
        image: "{{ name_image }}"
        state: started
        ports: 8080:8080        

#launch unit-file
    - name: copy unit
      ansible.builtin.copy:
        src: ./file/start-docker.service
        dest: /etc/systemd/system/start-docker.service

    - name: Enabled service
      ansible.builtin.service:
        name: start-docker
        enabled: yes